WebRole1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebRole1.Infra;

namespace WebRole1.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
	        var user = Request.GetCurrentSession();
			if (user != null)
				return Redirect("/Timeline");


            return View();
        }
    }
}

WebRole1/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Hammock;
using Hammock.Authentication.OAuth;
using WebRole1.Infra;
using WebRole1.Models;

namespace WebRole1.Controllers
{
	public class SignInController : Controller
	{
		//
		// GET: /SignIn/
		public ActionResult Index()
		{
			ServicePointManager.Expect100Continue = false;

			var credentials = new OAuthCredentials
			{
				Type = OAuthType.RequestToken,
				SignatureMethod = OAuthSignatureMethod.HmacSha1,
				ParameterHandling = OAuthParameterHandling.HttpAuthorizationHeader,
				ConsumerKey = Settings.ConsumerKey,
				ConsumerSecret = Settings.ConsumerSecret,
				CallbackUrl = "http://" + (Request.IsLocal ? "127.0.0.1" + ":" + Request.Url.Port : Request.Url.Host) + "/SignIn/TwitterCallback",
			};

			var client = new RestClient
			{
				Authority = "https://twitter.com/oauth",
				Credentials = credentials
			};

			var request = new RestRequest
			{
				Path = "/request_token"
			};

			RestResponse response = client.Request(request);
//
//			try
//			{
				var collection = HttpUtility.ParseQueryString(response.Content);
				Session["requestSecret"] = collection[1];

				return Redirect("https://twitter.com/oauth/authorize?oauth_token=" + collection[0]);
//			}
//			catch (Exception ex)
//			{
//				return Json(new { qs = response }, JsonRequestBehavior.AllowGet);
//			}
		}

		public ActionResult TwitterCallBack(string oauth_token, string oauth_verifier)
		{
			var requestSecret = (String)Session["requestSecret"];

			if (String.IsNullOrEmpty(oauth_token) || String.IsNullOrEmpty(requestSecret))
			{
				ViewBag.Message = "Token or verifier have not been provided.";
				return Redirect("/?denied");
			}

			// Grab data from Twitter
			var credentials = new OAuthCredentials
			{
				Type = OAuthType.AccessToken,
				SignatureMethod = OAuthSignatureMethod.HmacSha1,
				ParameterHandling = OAuthParameterHandling.HttpAuthorizationHeader,
				ConsumerKey = Settings.ConsumerKey,
				ConsumerSecret = Settings.ConsumerSecret,
				Token = oauth_token,
				TokenSecret = requestSecret,
				Verifier = oauth_verifier
			};

			var client = new RestClient()
			{
				Authority = "https://twitter.com/oauth",
				Credentials = credentials
			};

			var response = client.Request(new RestRequest
			{
				Path = "/access_token"
			});

			var responseCollection = HttpUtility.ParseQueryString(response.Content);

			ViewBag.Message = "";

			var accessToken = responseCollection["oauth_token"];
			var accessSecret = responseCollection["oauth_token_secret"];
			var userID = Int32.Parse(responseCollection["user_id"]);
			var screenName = responseCollection["screen_name"];

			AuthSession authSession;

			// Save session & user to db
			using (var db = new DatabaseEntities())
			{

				var user = db.Users.SingleOrDefault(u => u.UserId == userID);
				if (user == null)
				{
					user = new User()
					       	{
					       		ScreenName = screenName,
					       		UserId = userID,
								Secret = accessSecret,
								Token = accessToken
					       	};

					db.Users.AddObject(user);
				}
				else
				{
					user.Secret = accessSecret;
					user.Token = accessToken;
				}


				 authSession = new AuthSession()
				                  	{
				                  		SessionId = Guid.NewGuid(),
				                  		User = user,
				                  		Created = DateTime.Now
				                  	};

				db.AuthSessions.AddObject(authSession);
				db.SaveChanges();
			} 

			// Remember this user
//			Response.Cookies.Add(new HttpCookie("sid", authSession.SessionId.ToString()) { Expires = DateTime.Now.AddYears(5) });
			FormsAuthentication.SetAuthCookie(authSession.SessionId.ToString(), true);

			return RedirectToAction("Index", "Timeline");
		}

		public ActionResult SignOut()
		{
			FormsAuthentication.SignOut();
			return Redirect("~/");
		}
	}
}

WebRole1/Views/Home/Index.cshtml
@{
	Layout = null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
  <title>Buster &ndash; Twitter client for commute</title>
  <meta name="viewport" content="width=device-width">
  @Html.Partial("_Favicon")

  @Styles.Render("~/Content/homepage")
  @Html.Partial("_Tracking")
</head>
<body>
	<div id="c">
		<a href="@Url.Action("Index", "SignIn")" id="signing"><img src="/images/welcome_desktop.png" /></a>
	</div>
	<div id="f">
		<ul class="links">
			<li id="madein">Proudly built in Seattle</li>
			<li><a id="pledge-link" href="#" onclick="return togglePledge();">Our pledge</a></li>
			<li><a href="http://twitter.com/busterhq">Follow us</a></li>
		</ul>
		<div id="pledge">
			<ul>
				<li>Remember what you've already read</li>
				<li>Show tweets from your friends first (pin 'em!)</li>
				<li>Make following stories easier</li>
			</ul>
		</div>
	</div>
	<script type="text/javascript">
		// <![CDATA[
		function togglePledge() {
			var f = document.getElementById('f');
			if (f.className == '')
				f.className = 'showpledge';
			else
				f.className = '';

			return false;
		}
		// ]]>
	</script>
</body>
</html>